// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tmdb-layouts/EditorialLayout.tsx": () => import("../components/mockups/tmdb-layouts/EditorialLayout.tsx"),
  "./components/mockups/tmdb-layouts/ListLayout.tsx": () => import("../components/mockups/tmdb-layouts/ListLayout.tsx"),
  "./components/mockups/tmdb-layouts/SidebarLayout.tsx": () => import("../components/mockups/tmdb-layouts/SidebarLayout.tsx")
};
